export const FETCH_NEWS = 'FETCH_NEWS'
export const FETCH_DETAILS = 'FETCH_DETAILS'
export const SET_REFRESH = 'SET_REFRESH'
export const SEARCH_NEWS = 'SEARCH_NEWS'
export const COPY_NEWS = 'COPY_NEWS'